version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade heads; gunicorn --workers=3 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker hotel_app.main:app'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    depends_on:
      - db
      - redis
    env_file:
      - .env
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5431:5432
    restart: always

  redis:
      image: redis:6.2-alpine
      restart: always
      ports:
        - 6379:6379
      volumes: 
        - redis:/data
volumes:
  postgres_data:
  redis:
    driver: local